# Generated by Django 5.1.6 on 2025-02-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
