# Generated by Django 5.1.6 on 2025-02-13 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
