# Generated by Django 5.1.6 on 2025-02-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_part_part_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.IntegerField(max_length=155, unique=True),
        ),
    ]
