# Generated by Django 5.1.6 on 2025-02-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_remove_part_updated_at_alter_part_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.IntegerField(unique=True),
        ),
    ]
