# Generated by Django 5.1.6 on 2025-02-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_alter_part_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
