# Generated by Django 5.1.6 on 2025-02-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
